### ISSUE TITLE
Can't install with pip from pypi

### ISSUE THREAD

**Issue by zero-stroke** [kayvane1/brave-api#43]
When trying `pip install brave-search` I got this error:

pip install brave-search 
Collecting brave-search
  Using cached brave_search-0.2.0-py3-none-any.whl.metadata (5.8 kB)
ERROR: Exception:
Traceback (most recent call last):
  File "F:\envs\alg11\Lib\site-packages\pip\_vendor\packaging\requirements.py", line 102, in __init__
    req = REQUIREMENT.parseString(requirement_string)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\envs\alg11\Lib\site-packages\pip\_vendor\pyparsing\util.py", line 256, in _inner
    return fn(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\envs\alg11\Lib\site-packages\pip\_vendor\pyparsing\core.py", line 1190, in parse_string
    raise exc.with_traceback(None)
pip._vendor.pyparsing.exceptions.ParseException: Expected string_end, found '('  (at char 6), (line:1, col:7)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "F:\envs\alg11\Lib\site-packages\pip\_internal\cli\base_command.py", line 180, in exc_logging_wrapper
    status = run_func(*args)
             ^^^^^^^^^^^^^^^
  File "F:\envs\alg11\Lib\site-packages\pip\_internal\cli\req_command.py", line 245, in wrapper
    return func(self, options, args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\envs\alg11\Lib\site-packages\pip\_internal\commands\install.py", line 377, in run
    requirement_set = resolver.resolve(
                      ^^^^^^^^^^^^^^^^^
  File "F:\envs\alg11\Lib\site-packages\pip\_internal\resolution\resolvelib\resolver.py", line 95, in resolve
    result = self._result = resolver.resolve(
                            ^^^^^^^^^^^^^^^^^
  File "F:\envs\alg11\Lib\site-packages\pip\_vendor\resolvelib\resolvers.py", line 546, in resolve
    state = resolution.resolve(requirements, max_rounds=max_rounds)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\envs\alg11\Lib\site-packages\pip\_vendor\resolvelib\resolvers.py", line 427, in resolve
    failure_causes = self._attempt_to_pin_criterion(name)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\envs\alg11\Lib\site-packages\pip\_vendor\resolvelib\resolvers.py", line 239, in _attempt_to_pin_criterion
    criteria = self._get_updated_criteria(candidate)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\envs\alg11\Lib\site-packages\pip\_vendor\resolvelib\resolvers.py", line 229, in _get_updated_criteria
    for requirement in self._p.get_dependencies(candidate=candidate):
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\envs\alg11\Lib\site-packages\pip\_internal\resolution\resolvelib\provider.py", line 244, in get_dependencies
    return [r for r in candidate.iter_dependencies(with_requires) if r is not None]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\envs\alg11\Lib\site-packages\pip\_internal\resolution\resolvelib\provider.py", line 244, in <listcomp>
    return [r for r in candidate.iter_dependencies(with_requires) if r is not None]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\envs\alg11\Lib\site-packages\pip\_internal\resolution\resolvelib\candidates.py", line 239, in iter_dependencies
    for r in requires:
  File "F:\envs\alg11\Lib\site-packages\pip\_internal\metadata\importlib\_dists.py", line 221, in iter_dependencies
    req = Requirement(req_string)
          ^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\envs\alg11\Lib\site-packages\pip\_vendor\packaging\requirements.py", line 104, in __init__
    raise InvalidRequirement(
pip._vendor.packaging.requirements.InvalidRequirement: Parse error at "'(>=0.24.'": Expected string_end

This is within a conda environment, I tried with an old one and a new one, neither worked. 

I was able to successfully install by instead doing `pip install git+https://github.com/kayvane1/brave-api`

Windows, python 3.11, pip 24.0

**Comment by colintbowers** [comment]
Exact same issue here, and the fix worked for me. Environment is Ubuntu 22.04 LTS, pip 24.0, python 3.10.

**Comment by solovieff** [comment]
Same here.
